name: Build

on: [push, pull_request]

jobs:
  Build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
        - { name: Windows, os: windows-latest }
        - { name: Linux,   os: ubuntu-20.04, flags: -GNinja }
        - { name: MacOS,   os: macos-latest }
    steps:
    - name: Setup Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build
    - name: Get SDL2 headers
      uses: actions/checkout@v2
      with:
        name: libsdl-org/SDL
        ref: refs/tags/release-2.0.14
        path: SDL2
    - name: Get sdl12-compat sources
      uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -DCMAKE_C_FLAGS="-I${GITHUB_WORKSPACE}/SDL2/include" -B build ${{ matrix.platform.flags }}
    - name: Build
      run: cmake --build build/

